server:
    applicationContextPath: ${HTTP_CONTEXT_PATH:-/}
    applicationConnectors:
        - type: http
          port: 8080
          # time before the request expires
          idleTimeout: 180 seconds
    adminConnectors:
        - type: http
          port: 8089

logging:
    level: INFO
    loggers:
        "eu.clarin": ${LOG_LEVEL:-DEBUG}

switchboard:
    tikaConfigPath: ./tikaConfig.xml
    contactEmail: ${CONTACT_EMAIL:-switchboard@clarin.eu}
    tools:
        toolRegistryPath: ${REGISTRY_TOOL_PATH:-../../switchboard-tool-registry/tools}
        logoRegistryPath: ${REGISTRY_LOGO_PATH:-../../switchboard-tool-registry/logos}
        showOnlyProductionTools: ${REGISTRY_PRODUCTIONTOOLS_ONLY:-false}
    dataStore:
        location: # e.g. /my/data; defaults to temporary storage
        eraseAllStorageOnStart: ${DATASTORE_STARTERASE:-false}
        maxSize: ${DATASTORE_MAX_FILESIZE:-5M}
        maxLifetime: ${DATASTORE_MAX_FILELT:-2}
        maxLifetimeUnit: ${DATASTORE_FILELT_UNIT:-hours}
        cleanupPeriod: ${DATASTORE_CLEANPERIOD:-13}
        cleanupPeriodUnit: ${DATASTORE_CLEANPERIOD_UNIT:-minutes}
    urlResolver:
        connectTimeout: ${URLRESOLVER_CONNECTTIMEOUT:-3}
        readTimeout: ${URLRESOLVER_READTIMEOUT:-3}
        unit: ${URLRESOLVER_TIMEOUT_UNIT:-seconds}
        maxHttpCacheEntries: ${URLRESOLVER_MAX_HTTPCACHE_ENTRIES:-256}
