server:
    applicationContextPath: ${LRS_CONTEXT_PATH:-/}
    applicationConnectors:
        - type: http
          port: 8080
          # time before the request expires
          idleTimeout: 180 seconds
    adminConnectors:
        - type: http
          port: 8089

logging:
    level: INFO
    loggers:
        "eu.clarin": ${LRS_LOG_LEVEL:-DEBUG}

switchboard:
    tikaConfigPath: ./tikaConfig.xml
    contactEmail: ${LRS_CONTACT_EMAIL:-switchboard@clarin.eu}
    tools:
        toolRegistryPath: ${LRS_TOOL_REGISTRY_PATH:-../../switchboard-tool-registry/tools}
        logoRegistryPath: ${LRS_LOGO_REGISTRY_PATH:-../../switchboard-tool-registry/logos}
        showOnlyProductionTools: ${LRS_PRODUCTION_TOOLS_ONLY:-false}
    dataStore:
        location: # e.g. /my/data; defaults to temporary storage
        eraseAllStorageOnStart: ${LRS_DATASTORE_ERASEATSTART:-false}
        maxSize: ${LRS_DATASTORE_MAXSIZE:-5M}
        maxLifetime: ${LRS_DATASTORE_MAXLIFETIME:-2}
        maxLifetimeUnit: ${LRS_DATASTORE_MAXLIFETIME_UNIT:-hours}
        cleanupPeriod: ${LRS_DATASTORE_CLEANUPPERIOD:-13}
        cleanupPeriodUnit: ${LRS_DATASTORE_CLEANUPPERIOD_UNIT:-minutes}
    urlResolver:
        connectTimeout: ${LRS_URLRESOLVER_CONNECTTIMEOUT:-3}
        readTimeout: ${LRS_URLRESOLVER_READTIMEOUT:-3}
        unit: ${LRS_URLRESOLVER_TIMEOUTUNIT:-seconds}
